"""empty message

Revision ID: 86ee048c16ad
Revises: ed3f316b09b3
Create Date: 2018-11-29 14:56:37.532648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ee048c16ad'
down_revision = 'ed3f316b09b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entry', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entry', type_='foreignkey')
    op.drop_column('entry', 'author_id')
    # ### end Alembic commands ###
